# IMPORTANT: velocity in testing (modifiable)
velocity: 4

# IMPORTANT: vel_max and acc_max in training
vel_max_train: 6.0
acc_max_train: 6.0

# IMPORTANT: weight of costs for unit speed
wg: 0.15
ws: 10.0
wa: 1.0
wc: 1.0

# dataset
dataset_path: "../dataset_swarm"
image_height: 96
image_width: 160

# trajectory and primitive param
horizon_num: 5
vertical_num: 3
horizon_camera_fov: 90.0
vertical_camera_fov: 60.0
horizon_anchor_fov: 30.0
vertical_anchor_fov: 30.0
radio_range: 5.0
radio_num: 1

# safety penalties
d0: 1.2
r: 0.6

# distribution for unit state sampling
vx_mean_unit: 0.4
vy_mean_unit: 0.0
vz_mean_unit: 0.0
vx_std_unit: 2.0
vy_std_unit: 0.45
vz_std_unit: 0.3
ax_mean_unit: 0.0
ay_mean_unit: 0.0
az_mean_unit: 0.0
ax_std_unit: 0.5
ay_std_unit: 0.5
az_std_unit: 0.3
goal_pitch_std: 10.0
goal_yaw_std: 20.0

# extend the map to avoid trajectory exceeding bounds
map_expand_min: [0, 0, 0.2]
map_expand_max: [0, 0, 6.0]
